### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by pitr-ch** [graalvm/truffleruby#59]
- [x] ~~Supply a curl-able download that doesn't need an account or a click-through to use.~~ moved to #118

- [x] #83 Document how to add Ruby from GraalVM to a Ruby manager.

- [x] After untaring GraalVM, truffleruby has to work including other executable like irb, rake (they have to run on truffleruby). Solved with a helper directory lib/bin. Gem install uses absolute path in the executable wrappers installed to bindir, therefore they will run correctly on truffleruby.

- [x] GraalVM language/ruby directory has to have regular ruby layout so it can be added to ruby managers. Only know problem is that language/ruby/bin directory is missing. It should be a copy of truffleruby/bin directory. Two launchers in graalvm/bin and truffleruby/bin has to be sorted out. Ideally merged.

- [x] #60 Gem executable should be installed in truffleruby/bin next to the launcher as in other Rubies.

- [x] #60 When truffleruby is executed from GraalVM directly without a ruby manager and a ruby manager is in use configuring wrong GEM_HOME for a different ruby implementation a warning should be printed.

- [x] #46 Run bundler and gem without manually requiring `bundler-workarounds`

**Comment by pitr-ch** [comment]
I'll link a PR for the last two shortly.
cc @graalvm/truffleruby

**Comment by pitr-ch** [comment]
Last 2 are addressed in #60
cc @graalvm/truffleruby

**Comment by chrisseaton** [comment]
The final task here is to supply a `curl`-able download that doesn't need an account or a click-through to use.

**Comment by ioquatix** [comment]
Does `rvm use truffleruby` work yet?

**Comment by eregon** [comment]
@ioquatix Yes, although I assume you mean installing with RVM: https://github.com/oracle/truffleruby/issues/1062#issuecomment-404847171
